export type ProjectTag = 'Policy brief' | 'Publication' | 'Work in progress';

export interface Project {
  id: string;
  title: string;
  description: string;
  abstract: string;
  thumbnail: string;
  tags: ProjectTag[];
  link: string;
  journal?: string;
  authors?: string;
  date?: string; // ISO format (YYYY-MM-DD)
}


export const projects: Project[] = [
  {
    id: '1',
    title: 'What People Think and Want - Accra',
    description: 'Policy brief on pollution perceptions and policy preferences in Accra, Ghana.',
    abstract: 'Air pollution in Accra is widely recognised as a serious environmental and health issue, yet little is known about how respondents prioritise the problem, where they place responsibility, and which types of policy responses they ind acceptable. To address these questions, we conducted a city-wide survey in early 2025 with 1,750 respondents. The results offer new insights into public perceptions of air pollution, responsibility attribution, and support for a range of mitigation policies in Accra.',
    thumbnail: '/Images/Thumbnails/thumbnail_accra.jpeg',
    tags: ['Policy brief'],
    link: 'https://ib.ethz.ch/research/air-pollution/what-people-think/accra.html',
    journal: undefined,
    authors: 'Olga Kochkareva, Andina Nabilla, David N. Kollmann, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '2',
    title: 'Beyond the haze: Decomposing the effect of economic inequality on global air quality from 2000 to 2020',
    description: 'Study on relationship between economic inequality and air pollution within and between countries.',
    abstract: 'Extant research has analysed the macroeconomic and political drivers of worldwide air pollution. Empirically, studies have focused on either between-country (cross-national comparisons) or within-country (temporal changes) dynamics, but these related effects have not been simultaneously addressed. Employing a comprehensive dataset spanning 156 countries over two decades (2000−2020), we take a distinctive dual approach to examine the effects of economic inequality, economic development, and democratic institutions on air pollution exposure within and across countries. First, against expectations, we find that within countries over time, increases in economic inequality correlate with reduced air pollution. This relationship remains consistent irrespective of country-level economic development or democratic status. Further we find that the trajectory of economic inequality conditions this effect, suggesting that whether redistributive measures towards addressing economic inequality carry environmental co-benefits or trade-offs likely depends upon the context. Second, between countries, economic inequality has a limited association with air pollution levels. Third, the effects of economic inequality on air pollution levels within and between countries are substantively small in comparison to the impact of economic development and democracy. This study emphasises the need to reconsider conventional expectations regarding economic inequality, further accentuating the influence of economic development and democratic institutions.',
    thumbnail: '/Images/Thumbnails/thumbnail_beyond the haze.jpeg',
    tags: ['Publication'],
    link: 'https://www.sciencedirect.com/science/article/pii/S0921800924001071',
    journal: 'Ecological Economics',
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2024-05-15',
  },
  {
    id: '3',
    title: 'The Impact of Traffic and Meteorology on Urban Particle Mass and Particle Number Concentrations: Student-Led Studies Using Mobile Measurements before, during, and after the COVID-19 Pandemic Lockdowns',
    description: 'Student-led study on Covid effects on urban air pollution, using a cargo bicycle.',
    abstract: 'A series of student-led research activities were performed using a cargo bicycle equipped with air chemistry instrumentation to study the dynamics of aerosol particles in urban air before, during, and after the COVID-19 lockdown periods. The studies examined a high-traffic route and a low-traffic route around the city center of Münster, Germany. A complex picture emerged for how the particle number concentrations (PN) and particle mass concentrations (PM, specifically PM10) were affected by the day of the week, the route selected, the meteorological conditions, and the traffic intensity. Traffic had the most impact on PN through the multitude of exhaust plumes from motorized vehicles. The impact of traffic on PM10 was rather low, which is also mirrored in the general pattern of the low response of PM10 to the pandemic lockdown in Germany. Instead, PM10 responded more to the day of the week. Presumably, PM10 responds either to a specific traffic component, such as commercial low-duty vehicles, or to other business, such as construction activity. Meteorological conditions exert their impact mostly through the relative humidity, which affects particle growth. As such, future research could examine PN and PM10 responses over all seasons of the year. In any case, this student-led study in which high-resolution data were acquired deepened our understanding and broadened our view on particle dynamics in urban air. Well-trained university graduates will contribute to meeting further challenges in studying and combatting air pollution.',
    thumbnail: 'Images/Thumbnails/thumbnail_bike münster.jpeg',
    tags: ['Publication'],
    link: 'https://www.mdpi.com/2073-4433/13/1/62',
    journal: "Atmosphere",
    authors: 'Klemm et al.',
    date: '2021-12-30',
  },
  {
    id: '4',
    title: 'What People Think and Want - Delhi',
    description: 'Policy brief on pollution perceptions and policy preferences in Delhi, India.',
    abstract: 'Air pollution in Delhi is among the most severe globally, with PM2.5 and PM10 levels far exceeding World Health Organization guidelines. Yet, less is known about how people in Delhi perceive this challenge, who they believe should take responsibility, and which solutions they support. We conducted an online survey of 3,406 respondents in early 2025 to better understand public perceptions of air pollution and preferences for air quality policies.',
    thumbnail: 'Images/Thumbnails/thumbnail_delhi.jpeg',
    tags: ['Policy brief'],
    link: 'https://ib.ethz.ch/research/air-pollution/what-people-think/delhi.html',
    journal: undefined,
    authors: 'David N. Kollmann, Andina Nabilla, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière,E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '5',
    title: 'What People Think and Want - Jakarta',
    description: 'Policy brief on pollution perceptions and policy preferences in Jakarta, Indonesia.',
    abstract: 'Air pollution in Jakarta is widely recognised as a serious public health and environmental threat; yet, until now, little was known about how residents themselves perceive the problem, who they expect to act, and which policy solutions they are willing to support. To fill this gap, we surveyed 3,400 Jakarta residents online in February-March 2025',
    thumbnail: 'Images/Thumbnails/thumbnail_jakarta.jpeg',
    tags: ['Policy brief'],
    link: 'https://ib.ethz.ch/research/air-pollution/what-people-think/jakarta.html',
    journal: undefined,
    authors: 'Andina Nabilla, David N. Kollmann, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '7',
    title: 'What People Think and Want - Johannesburg',
    description: 'Policy brief on pollution perceptions and policy preferences in Johannesburg, South Africa.',
    abstract: 'Air pollution in Johannesburg is a pressing public health and environmental issue, but it is unclear how much people perceive air pollution, who they believe should take responsibility, and the kinds of air quality policies they are willing to support. We conducted a comprehensive survey (online and in-person) in early 2025 with over 3,000 respondents from the City of Johannesburg to identify their perceptions of localised air quality and their policy preference',
    thumbnail: 'Images/Thumbnails/thumbnail_joburg.jpeg',
    tags: ['Policy brief'],
    link: 'https://ib.ethz.ch/research/air-pollution/what-people-think/johannesburg.html',
    journal: undefined,
    authors: 'Andina Nabilla, David N. Kollmann, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '9',
    title: 'Can Democracy Protect Lower-Income Countries From Becoming Pollution Havens?',
    description: 'Publication on democracy mitigating pollution haven effects in lower-income countries.',
    abstract: 'Lower-income countries absorb a substantial part of other countries’ consumption-related environmental footprints, with international trade and foreign direct investment (FDI) serving as the conduit for this environmental “insourcing.” We examine whether democratic institutions could help mitigate the risk of lower-income countries becoming pollution havens in this context. Using data on CO2 emissions for all non-OECD countries in 1990–2019, we find that democratic institutions can indeed mitigate the otherwise pollution-increasing effect of trade and FDI. Substantively, this mitigation effect is in the order of 0.14 metric tons of CO2 per capita and, thus, quite substantial. We also observe similar effects for more broadly defined environmental footprint measures. Overall, the evidence we present is consistent with the expectation that democracy helps in protecting lower-income countries against disproportionately accumulating polluting economic activity in an open global economy.',
    thumbnail: 'Images/Thumbnails/thumbnail_pollution havens2.jpeg',
    tags: ['Publication'],
    link: 'https://journals.sagepub.com/doi/full/10.1177/10704965251317436',
    journal: "The Journal of Environment & Development",
    authors: 'Thomas Bernauer, Tobias Böhmelt, Ella Henninger',
    date: '2025-02-01',
  },
  {
    id: '10',
    title: 'Persistent inequalities in global air quality monitoring should not delay pollution mitigation',
    description: 'Publication on inequalities in global air quality monitoring and implications for pollution mitigation.',
    abstract: 'Air pollution is a global health crisis that disproportionately affects lower- and middle-income countries. We examine global air quality monitoring data, highlighting persistent inequalities in high-exposure regions, and assess the potential of emerging technologies to improve data utility for mitigation. Improving air quality, however, does not need to wait for more data, nor will monitoring alone drive action. Immediate mitigation measures with broad cobenefits are needed now to reduce pollution, even in data-scarce settings.',
    thumbnail: 'Images/Thumbnails/thumbnail_persistent inequalities.jpeg',
    tags: ['Publication'],
    link: 'https://www.pnas.org/doi/abs/10.1073/pnas.2423259122',
    journal: "Proceedings of the National Academy of Sciences",
    authors: 'E. Keith Smith, Camille Fournier de Laurière, Ella Henninger',
    date: '2025-04-28',
  },
  {
    id: '11',
    title: 'Who Shapes Air Pollution Governance? How Economic Development, Democracy, and Data Condition Stakeholder Influence in Six Majority World Cities',
    description: 'Paper on how context shapes which stakeholders are most influential in shaping governments` mitigation agendas. Currently under review at Global Environmental Politics.',
    abstract: 'Air pollution is a major global health hazard, with the worst burden falling on cities in the Majority World. Yet which conditions shape governments willingness to act on air pollution remains poorly understood. Drawing on 63 semi-structured interviews of 72 air pollution experts and stakeholders in six highly polluted cities (Accra, Kampala, Johannesburg, Jakarta, Dhaka, Delhi), we examine how economic development, democracy, and data availability structure the influence of citizens, local advocates, economic elites, and country-external agencies on governmental mitigation efforts. We find that governments remain primarily responsive to economic elites across levels of economic development, while external actors play a stronger role in the lowest-income case, Dhaka. Democracy strengthens citizens and local advocates through electoral accountability and civil society mobilization. Data availability creates opportunities for influence but also provokes governmental counter-strategies. These findings highlight the centrality of stakeholder power in clean-air governance, showing how political, economic, and informational constraints shape whose demands governments respond to.',
    thumbnail: 'Images/Thumbnails/thumbnail_qual paper.png',
    tags: ['Publication'],
    link: '/research/contextual-stakeholder-influence',
    journal: 'Global Environmental Politics (accepted)',
    authors: 'Ella Henninger, E. Keith Smith, Thomas Bernauer',
    date: '2026-06-11',
  },
  {
    id: '12',
    title: 'Shifting environmental pollution abroad contributes to lower emissions in democracies',
    description: 'Publication on how pollution offshoring improves environmental records of democracies.',
    abstract: 'Many studies suggest that democracies have, on average, a better environmental protection record than authoritarian states. But this debate is far from resolved. Hence, we take a closer look at an overlooked factor that may shed new light on the ambiguous claims and findings of the democracy-environment nexus: pollution offshoring. We hypothesize that democracies can improve their record and become “greener” not only through genuinely domestic environmental protection, but also through outsourcing environmental impacts of their consumption to other countries. Analyzing data on greenhouse gas emissions, pollution offshoring, and democracy for more than 160 countries since the 1990s, we report evidence that the offshoring of environmental pollution contributes to the superior environmental record of democracies. The main policy implication is that democracies, per se, may not have a better environmental record than autocracies when considering global environmental impacts. This implies that democratic countries, in particular, should re-orient their environmental protection efforts from merely domestic to global environmental consequences of local economic activity.',
    thumbnail: 'Images/Thumbnails/thumbnail_shifting pollution.jpeg',
    tags: ['Publication'],
    link: 'https://journals.plos.org/climate/article?id=10.1371/journal.pclm.0000602',
    journal: 'PLOS Climate',
    authors: 'Thomas Bernauer, Tobias Böhmelt, Ella Henninger',
    date: '2025-05-14',
  },
  {
    id: '13',
    title: 'Strong demand for clean air policies in Majority World cities',
    description: 'Paper on perceptions of air pollution and support for mitigation policies in four Majority World cities.',
    abstract: 'Air pollution is a leading health risk, especially in large cities of the Majority World. In these emerging markets and developing economies, it remains unclear whether residents will demand mitigation, perceive it as a threat or view poor air quality as a necessary part of development. Competing theories predict either strong or weak support and cross-national evidence is scarce, particularly for measures of policy support. Here we surveyed 11,417 adults in 4 severely polluted cities—Accra, Delhi, Jakarta and Johannesburg. Air quality was a highly prioritized issue and overall levels of concern are very high. Majorities support six mitigation proposals, including cost-salient measures such as stricter industrial limits, increasing household electrification and expanding public transport. Concern, trust and low perceived behavioral control were the strongest correlates of support. People see air pollution, feel its effects and want governments to act, even when action entails economic costs, challenging views of limited environmental demand in highly exposed, economically developing settings.',
    thumbnail: 'Images/Thumbnails/thumbnail_strong demand.png',
    tags: ['Publication'],
    link: 'https://www.nature.com/articles/s44284-026-00451-x',
    journal:'Nature Cities',
    authors: 'E. Keith Smith, Ella Henninger, Camille Fournier de Laurière, Vally Koubi, Raeesa Moolla, Liam Beiser-McGrath, Thomas Bernauer',
    date: '2026-05-28',
  },
  {
    id: '14',
    title: '(Un)fair to Me - (Un)fair to You? Distributional Implications of Policies and Their Effect on Fairness and Policy Support',
    description: 'Paper project on how different distributional policy designs shape fairness perceptions and support in Delhi and Jakarta.',
    abstract: 'Public support for redistributive policies often hinges on fairness perceptions, yet it remains unclear whether these reflect broader normative principles or merely track material self-interest; a distinction with direct implications for whether policy designs can increase public acceptance. We distinguish two evaluative processes: fairness-to-me, a self-oriented normative judgement of one`s own treatment, and fairness-to-others, a normative judgement of whether the distribution of costs and benefits across societal groups is appropriate. Using a pre-registered 2×2 factorial vignette experiment with approximately 3,400 respondents in Delhi and Jakarta, we vary who pays and who benefits across urban transport policies. Car ownership as a proxy for material stakes shifts fairness-to-me but not fairness-to-others, showing the two dimensions respond differently to personal exposure. Benefit targeting provokes stronger fairness backlash than cost targeting, especially in Jakarta. These findings imply more political space for redistributive policies than accounts reducible to self-interest would predict.',
    thumbnail: 'Images/Thumbnails/thumbnail_fairness.png',
    tags: ['Work in progress'],
    link: '/research/fairness',
    journal: undefined,
    authors: 'Ella Henninger, Liam Beiser-McGrath, Vally Koubi',
    date: '2025-01-03',
  },
  {
    id: '15',
    title: 'Building Bridges: Actor Involvement, Political Trust, and Environmental Policy Support',
    description: 'Paper project on the role of actor involvement in increasing policy support among low-trusting individuals in Accra, Johannesburg, Jakarta, and Delhi.',
    abstract: 'Ambitious public policies often require citizens to accept near-term costs for delayed or uncertain benefits. I argue that inclusive policy design—involving local experts, international organisations, or business actors—can increase support by signalling effectiveness and procedural fairness, particularly among low-trust citizens. Yet broader coalitions may trigger perceived governance drawbacks such as coordination problems or blurred accountability. A pre-registered survey experiment in Accra, Johannesburg, Jakarta, and Delhi on local air quality policy shows that inclusive design increases support relative to government-only design, with the largest gains among low-trust respondents. Involving a single trusted non-governmental actor raises support to levels comparable with broader coalitions. Perceived effectiveness and fairness move with support more strongly than concerns over coordination or accountability, suggesting these drawbacks are not salient in this setting. These findings imply that inclusive design can function as a credibility signal, providing evidence on how democratic innovations shape policy support in Majority World contexts.',
    thumbnail: 'Images/Thumbnails/thumbnail_trust.png',
    tags: ['Work in progress'],
    link: '/research/trust',
    journal: undefined,
    authors: 'Ella Henninger',
    date: '2025-01-04',
  },
  {
    id: '16',
    title: 'Pollution, Government (Dis)satisfaction, and Demand for Abatement Policies',
    description: 'Paper project on the effect of pollution on political attitudes in Accra, using daily variation in pollution levels as plausibly exogeneous treatment.',
    abstract: 'How chronic environmental stressors influence political behavior remains a critical yet under-researched question in environmental politics. While existing literature focuses on acute weather events, this study examines whether day-to-day fluctuations in air pollution shape political attitudes and policy preferences. Theoretically, we propose two mechanisms: an egotropic pathway, where physical discomfort increases the salience of pollution, and a systemic pathway, where visible smog serves as a performance signal of government incapacity. These mechanisms may either mobilize support for abatement or, if trust is sufficiently eroded, induce skepticism toward state-led solutions. Utilizing a pre-registered quasi-experimental design, we link daily ambient air quality data to a survey of approximately 1,750 residents in Accra, Ghana. As a rapidly urbanizing, democratic, lower-middle-income context, Accra provides a stringent test for the generalizability of findings previously limited to China. Our results indicate that, despite high exposure, daily pollution variation has limited impact on citizens\' concern, perceived government capacity, or overall satisfaction with the state. While correlational links between environmental concern and policy demand remain strong, the causal effect of short-term pollution spikes is significantly smaller than in previous studies. These findings suggest important scope conditions for environmental signaling; in contexts where pollution competes with pressing developmental priorities like infrastructure and housing, the chain linking degradation to political mobilization may weaken. Academically, this study clarifies how habituation and competing salience blunt environmental accountability. Societally, it underscores the need for strategic public communication to bridge the gap between objective environmental risks and public demand for policy action.',
    thumbnail: 'Images/Thumbnails/thumbnail_jop_accra.jpeg',
    tags: ['Work in progress'],
    link: '/research/jop',
    journal: undefined,
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2025-01-02',
  },
  {
    id: '17',
    title: 'Citizens or the State: Trust and Responsibility Attribution for Pollution Mitigation Across 39 African Countries',
    description: 'Work in progress. In this paper, we study how trust shapes who citizens believe to be responsible for pollution mitigation.',
    abstract: 'Democratic accountability requires that citizens correctly identify who is responsible for public problems. Yet responsibility attribution is often subject to biases that colour judgements of credit and blame. While partisanship has been the most studied such perceptual screen, recent work suggests that trust may play an analogous role in shaping whether responsibility for collective problems is directed at governments or at citizens themselves. We provide direct evidence for this mechanism, positioning political and social trust as factors structuring responsibility attribution for pollution mitigation across 39 African countries using Afrobarometer Round 9 (2021–23). Drawing on a framework that distinguishes forward-looking desired responsibility from backward-looking causal responsibility, we argue that the same level of trust can generate opposite attribution patterns depending on which conception dominates. Using logistic regressions with country-fixed effects, we find that higher political trust is associated with lower government responsibility attribution, consistent with a blame rather than capacity logic, while higher social trust is associated with higher government responsibility attribution, suggesting a citizen-blame dynamic under low social trust. These findings contribute to debates on democratic accountability and collective action, where the individualisation of responsibility for structural problems may reduce political pressure on governments to act.',
    thumbnail: 'Images/Thumbnails/thumbnail_afrobarometer.png',
    tags: ['Work in progress'],
    link: '/research/afrobarometer',
    journal: undefined,
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2025-01-01',
  },
  {
    id: '18',
    title: 'Global blind spots in air pollution public opinion: an LLM-assisted mapping of research coverage and survey availability',
    description: 'Paper on the state of research on public views on air pollution, using a novel LLM-assisted workflow to map the literature and survey item coverage.',
    abstract: 'Air pollution is a global health crisis, but evidence on public perceptions of pollution exposure and mitigation demands remains fragmented. We first map "what research covers" by reviewing the survey-based literature on public views of air pollution, coding 456 studies through a transparent, LLM-assisted screening and classification workflow. Then, we map "what surveys offer" by cataloging 112 air-quality survey items in cross-national survey programs, coding them manually using the same classification framework. We find persistent geographic and exposure-level biases: survey-based research focuses on high-income countries, China and India, while cross-national item coverage is more clustered in Europe. Thematically, both domains emphasize perceptions, with gaps in behavior, policy preferences, and health—particularly in high-exposure regions. These findings highlight that where mitigation is most needed, research coverage is most limited and accessible survey data most scarce. Methodologically, the paper develops a validated LLM-assisted workflow to facilitate future large-scale literature mapping and classification.',
    thumbnail: 'Images/Thumbnails/thumbnail_GPT.png',
    tags: ['Publication'],
    link: 'https://iopscience.iop.org/article/10.1088/1748-9326/ae7132/meta',
    journal: 'Environmental Research Letters',
    authors: 'Ella Henninger, Camille Fournier de Lauriere, Andina Nabilla, Raeesa Moolla, E. Keith Smith',
    date: '2026-05-21',
  },
  {
    id: '19',
    title: 'Public support for clean-air action in polluted cities',
    description: 'Policy brief on public support for clean-air policies in four Majority World cities, based on a survey of over 11,000 respondents.',
    abstract: 'In four major cities that face severe exposure, air pollution is not a hidden or low-priority issue. Respondents express concern about poor air quality and want their governments to act. Rather than constraining action, public opinion may give policymakers the confidence to implement ambitious clean air policies without fear of public backlash.',
    thumbnail: 'Images/Thumbnails/thumbnail_policybrief_NC.png',
    tags: ['Policy brief'],
    link: 'https://www.nature.com/articles/s44284-026-00455-7',
    journal: 'Nature Cities',
    authors: 'Ella Henninger, E. Keith Smith, Camille Fournier de Lauriere, Vally Koubi, Raeesa Moolla, Liam Beiser-McGrath, Thomas Bernauer',
    date: '2026-05-28',
  }
];
