export type ProjectTag = 'Policy brief' | 'Publication' | 'Work in progress';

export interface Project {
  id: string;
  title: string;
  description: string;
  abstract: string;
  thumbnail: string;
  tags: ProjectTag[];
  link: string;
  journal?: string;
  authors?: string;
  date?: string; // ISO format (YYYY-MM-DD)
}


export const projects: Project[] = [
  {
    id: '1',
    title: 'What People Think and Want - Accra',
    description: 'Policy brief on pollution perceptions and policy preferences in Accra, Ghana.',
    abstract: 'Air pollution in Accra is widely recognised as a serious environmental and health issue, yet little is known about how respondents prioritise the problem, where they place responsibility, and which types of policy responses they ind acceptable. To address these questions, we conducted a city-wide survey in early 2025 with 1,750 respondents. The results offer new insights into public perceptions of air pollution, responsibility attribution, and support for a range of mitigation policies in Accra.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_accra.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief-accra',
    journal: undefined,
    authors: 'Olga Kochkareva, Andina Nabilla, David N. Kollmann, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '2',
    title: 'Beyond the haze: Decomposing the effect of economic inequality on global air quality from 2000 to 2020',
    description: 'Study on relationship between economic inequality and air pollution within and between countries.',
    abstract: 'Extant research has analysed the macroeconomic and political drivers of worldwide air pollution. Empirically, studies have focused on either between-country (cross-national comparisons) or within-country (temporal changes) dynamics, but these related effects have not been simultaneously addressed. Employing a comprehensive dataset spanning 156 countries over two decades (2000−2020), we take a distinctive dual approach to examine the effects of economic inequality, economic development, and democratic institutions on air pollution exposure within and across countries. First, against expectations, we find that within countries over time, increases in economic inequality correlate with reduced air pollution. This relationship remains consistent irrespective of country-level economic development or democratic status. Further we find that the trajectory of economic inequality conditions this effect, suggesting that whether redistributive measures towards addressing economic inequality carry environmental co-benefits or trade-offs likely depends upon the context. Second, between countries, economic inequality has a limited association with air pollution levels. Third, the effects of economic inequality on air pollution levels within and between countries are substantively small in comparison to the impact of economic development and democracy. This study emphasises the need to reconsider conventional expectations regarding economic inequality, further accentuating the influence of economic development and democratic institutions.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_beyond the haze.jpeg',
    tags: ['Publication'],
    link: '/research/beyond-the-haze',
    journal: 'Ecological Economics',
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2024-05-15',
  },
  {
    id: '3',
    title: 'AI in Social Sciences',
    description: 'Ongoing research on the impact of AI in social sciences.',
    abstract: 'This work in progress investigates the applications and implications of artificial intelligence in social science research.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_bike münster.jpeg',
    tags: ['Work in progress'],
    link: '/research/ai-social',
    journal: undefined,
    authors: 'Ella Henninger, Alex Kim',
    date: '2025-11-01',
  },
  {
    id: '4',
    title: 'What People Think and Want - Delhi',
    description: 'Policy brief on pollution perceptions and policy preferences in Delhi, India.',
    abstract: 'Air pollution in Delhi is among the most severe globally, with PM2.5 and PM10 levels far exceeding World Health Organization guidelines. Yet, less is known about how people in Delhi perceive this challenge, who they believe should take responsibility, and which solutions they support. We conducted an online survey of 3,406 respondents in early 2025 to better understand public perceptions of air pollution and preferences for air quality policies.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_delhi.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief-delhi',
    journal: undefined,
    authors: 'David N. Kollmann, Andina Nabilla, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière,E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '5',
    title: 'What People Think and Want - Jakarta',
    description: 'Policy brief on pollution perceptions and policy preferences in Jakarta, Indonesia.',
    abstract: 'Air pollution in Jakarta is widely recognised as a serious public health and environmental threat; yet, until now, little was known about how residents themselves perceive the problem, who they expect to act, and which policy solutions they are willing to support. To fill this gap, we surveyed 3,400 Jakarta residents online in February-March 2025',
    thumbnail: 'src/assets/Thumbnails/thumbnail_jakarta.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief-jakarta',
    journal: undefined,
    authors: 'Andina Nabilla, David N. Kollmann, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '6',
    title: 'Digital Literacy Study',
    description: 'Work in progress: digital literacy in rural communities.',
    abstract: 'This study examines the state of digital literacy in rural communities and proposes strategies for improvement.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_map münster.jpeg',
    tags: ['Work in progress'],
    link: '/research/digital-literacy',
    journal: undefined,
    authors: 'Ella Henninger, Sara Lee',
    date: '2025-08-01',
  },
  {
    id: '7',
    title: 'What People Think and Want - Johannesburg',
    description: 'Policy brief on pollution perceptions and policy preferences in Johannesburg, South Africa.',
    abstract: 'Air pollution in Johannesburg is a pressing public health and environmental issue, but it is unclear how much people perceive air pollution, who they believe should take responsibility, and the kinds of air quality policies they are willing to support. We conducted a comprehensive survey (online and in-person) in early 2025 with over 3,000 respondents from the City of Johannesburg to identify their perceptions of localised air quality and their policy preference',
    thumbnail: 'src/assets/Thumbnails/thumbnail_joburg.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief_joburg',
    journal: undefined,
    authors: 'Andina Nabilla, David N. Kollmann, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '8',
    title: 'Renewable Energy Publication',
    description: 'Publication on the adoption of renewable energy in developing countries.',
    abstract: 'This publication discusses the challenges and opportunities for renewable energy adoption in developing countries.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_pollution havens1.jpeg',
    tags: ['Publication'],
    link: '/research/renewable-energy',
    journal: 'Energy Policy',
    authors: 'Ella Henninger, Fatima Noor',
    date: '2022-11-20',
  },
  {
    id: '9',
    title: 'Water Security Work in Progress',
    description: 'Ongoing research on water security challenges in arid regions.',
    abstract: 'This project investigates water security issues in arid regions, focusing on sustainable management and policy.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_pollution havens2.jpeg',
    tags: ['Work in progress'],
    link: '/research/water-security',
    journal: undefined,
    authors: 'Ella Henninger, Omar Farouk',
    date: '2025-06-01',
  },
  {
    id: '10',
    title: 'Food Systems Policy Brief',
    description: 'Policy brief on resilient food systems for urban populations.',
    abstract: 'This brief examines strategies for building resilient food systems in urban environments.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_persistent inequalities.jpeg',
    tags: ['Policy brief'],
    link: '/research/food-systems',
    journal: undefined,
    authors: 'Ella Henninger, Maria Lopez',
    date: '2025-05-01',
  },
  {
    id: '11',
    title: 'Smart Cities Publication',
    description: 'Peer-reviewed publication on smart city technologies and governance.',
    abstract: 'This publication reviews smart city technologies and their impact on urban governance and quality of life.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_qual paper.png',
    tags: ['Publication'],
    link: '/research/smart-cities',
    journal: 'Smart Cities Review',
    authors: 'Ella Henninger, Tom Brown',
    date: '2023-03-15',
  },
  {
    id: '12',
    title: 'Climate Adaptation Work in Progress',
    description: 'Work in progress: climate adaptation strategies for coastal areas.',
    abstract: 'This project explores adaptation strategies for coastal areas facing climate change impacts.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_shifting pollution.jpeg',
    tags: ['Work in progress'],
    link: '/research/climate-adaptation',
    journal: undefined,
    authors: 'Ella Henninger, Lisa White',
    date: '2025-04-01',
  },
  {
    id: '13',
    title: 'Public Health Policy Brief',
    description: 'Policy brief on public health interventions in megacities.',
    abstract: 'This brief discusses public health interventions and challenges in large urban centers.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_strong demand.png',
    tags: ['Policy brief'],
    link: '/research/public-health',
    journal: undefined,
    authors: 'Ella Henninger, Chen Wang',
    date: '2025-03-01',
  }
];
