export type ProjectTag = 'Policy brief' | 'Publication' | 'Work in progress';

export interface Project {
  id: string;
  title: string;
  description: string;
  abstract: string;
  thumbnail: string;
  tags: ProjectTag[];
  link: string;
  journal?: string;
  authors?: string;
  date?: string; // ISO format (YYYY-MM-DD)
}


export const projects: Project[] = [
  {
    id: '1',
    title: 'What People Think and Want - Accra',
    description: 'Policy brief on pollution perceptions and policy preferences in Accra, Ghana.',
    abstract: 'Air pollution in Accra is widely recognised as a serious environmental and health issue, yet little is known about how respondents prioritise the problem, where they place responsibility, and which types of policy responses they ind acceptable. To address these questions, we conducted a city-wide survey in early 2025 with 1,750 respondents. The results offer new insights into public perceptions of air pollution, responsibility attribution, and support for a range of mitigation policies in Accra.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_accra.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief-accra',
    journal: undefined,
    authors: 'Olga Kochkareva, Andina Nabilla, David N. Kollmann, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '2',
    title: 'Beyond the haze: Decomposing the effect of economic inequality on global air quality from 2000 to 2020',
    description: 'Study on relationship between economic inequality and air pollution within and between countries.',
    abstract: 'Extant research has analysed the macroeconomic and political drivers of worldwide air pollution. Empirically, studies have focused on either between-country (cross-national comparisons) or within-country (temporal changes) dynamics, but these related effects have not been simultaneously addressed. Employing a comprehensive dataset spanning 156 countries over two decades (2000−2020), we take a distinctive dual approach to examine the effects of economic inequality, economic development, and democratic institutions on air pollution exposure within and across countries. First, against expectations, we find that within countries over time, increases in economic inequality correlate with reduced air pollution. This relationship remains consistent irrespective of country-level economic development or democratic status. Further we find that the trajectory of economic inequality conditions this effect, suggesting that whether redistributive measures towards addressing economic inequality carry environmental co-benefits or trade-offs likely depends upon the context. Second, between countries, economic inequality has a limited association with air pollution levels. Third, the effects of economic inequality on air pollution levels within and between countries are substantively small in comparison to the impact of economic development and democracy. This study emphasises the need to reconsider conventional expectations regarding economic inequality, further accentuating the influence of economic development and democratic institutions.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_beyond the haze.jpeg',
    tags: ['Publication'],
    link: '/research/beyond-the-haze',
    journal: 'Ecological Economics',
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2024-05-15',
  },
  {
    id: '3',
    title: 'The Impact of Traffic and Meteorology on Urban Particle Mass and Particle Number Concentrations: Student-Led Studies Using Mobile Measurements before, during, and after the COVID-19 Pandemic Lockdowns',
    description: 'Student-led study on Covid effects on urban air pollution, using a cargo bicycle.',
    abstract: 'A series of student-led research activities were performed using a cargo bicycle equipped with air chemistry instrumentation to study the dynamics of aerosol particles in urban air before, during, and after the COVID-19 lockdown periods. The studies examined a high-traffic route and a low-traffic route around the city center of Münster, Germany. A complex picture emerged for how the particle number concentrations (PN) and particle mass concentrations (PM, specifically PM10) were affected by the day of the week, the route selected, the meteorological conditions, and the traffic intensity. Traffic had the most impact on PN through the multitude of exhaust plumes from motorized vehicles. The impact of traffic on PM10 was rather low, which is also mirrored in the general pattern of the low response of PM10 to the pandemic lockdown in Germany. Instead, PM10 responded more to the day of the week. Presumably, PM10 responds either to a specific traffic component, such as commercial low-duty vehicles, or to other business, such as construction activity. Meteorological conditions exert their impact mostly through the relative humidity, which affects particle growth. As such, future research could examine PN and PM10 responses over all seasons of the year. In any case, this student-led study in which high-resolution data were acquired deepened our understanding and broadened our view on particle dynamics in urban air. Well-trained university graduates will contribute to meeting further challenges in studying and combatting air pollution.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_bike münster.jpeg',
    tags: ['Publication'],
    link: '/research/münster-pollution',
    journal: "Atmosphere",
    authors: 'Otto Klemm, Antonia Ahrens, Margarethe Arnswald, Raika Bethke, David Frederik Berger ,Katharina Blankenhaus, Lisa Blauth, Bettina Breuer, Sophia Buchholz, Felix Burek, Laura Ehrnsperger,Sarah Funken, Ella Henninger , Janik Hohl, Nadine Jöllenbeck, Philipp Kirgasser, Maike Kuhls, Bastian Paas ,Lea Andrea Roters, Carsten Schaller, Hanna Schlüter',
    date: '2021-12-30',
  },
  {
    id: '4',
    title: 'What People Think and Want - Delhi',
    description: 'Policy brief on pollution perceptions and policy preferences in Delhi, India.',
    abstract: 'Air pollution in Delhi is among the most severe globally, with PM2.5 and PM10 levels far exceeding World Health Organization guidelines. Yet, less is known about how people in Delhi perceive this challenge, who they believe should take responsibility, and which solutions they support. We conducted an online survey of 3,406 respondents in early 2025 to better understand public perceptions of air pollution and preferences for air quality policies.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_delhi.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief-delhi',
    journal: undefined,
    authors: 'David N. Kollmann, Andina Nabilla, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière,E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '5',
    title: 'What People Think and Want - Jakarta',
    description: 'Policy brief on pollution perceptions and policy preferences in Jakarta, Indonesia.',
    abstract: 'Air pollution in Jakarta is widely recognised as a serious public health and environmental threat; yet, until now, little was known about how residents themselves perceive the problem, who they expect to act, and which policy solutions they are willing to support. To fill this gap, we surveyed 3,400 Jakarta residents online in February-March 2025',
    thumbnail: 'src/assets/Thumbnails/thumbnail_jakarta.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief-jakarta',
    journal: undefined,
    authors: 'Andina Nabilla, David N. Kollmann, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '7',
    title: 'What People Think and Want - Johannesburg',
    description: 'Policy brief on pollution perceptions and policy preferences in Johannesburg, South Africa.',
    abstract: 'Air pollution in Johannesburg is a pressing public health and environmental issue, but it is unclear how much people perceive air pollution, who they believe should take responsibility, and the kinds of air quality policies they are willing to support. We conducted a comprehensive survey (online and in-person) in early 2025 with over 3,000 respondents from the City of Johannesburg to identify their perceptions of localised air quality and their policy preference',
    thumbnail: 'src/assets/Thumbnails/thumbnail_joburg.jpeg',
    tags: ['Policy brief'],
    link: '/research/policy-brief_joburg',
    journal: undefined,
    authors: 'Andina Nabilla, David N. Kollmann, Olga Kochkareva, Ella Henninger, Camille Fournier de Laurière, E. Keith Smith, Vally Koubi, Thomas Bernauer',
    date: '2025-06-30',
  },
  {
    id: '9',
    title: 'Can Democracy Protect Lower-Income Countries From Becoming Pollution Havens?',
    description: 'Publication on democracy mitigating pollution haven effects in lower-income countries.',
    abstract: 'Lower-income countries absorb a substantial part of other countries’ consumption-related environmental footprints, with international trade and foreign direct investment (FDI) serving as the conduit for this environmental “insourcing.” We examine whether democratic institutions could help mitigate the risk of lower-income countries becoming pollution havens in this context. Using data on CO2 emissions for all non-OECD countries in 1990–2019, we find that democratic institutions can indeed mitigate the otherwise pollution-increasing effect of trade and FDI. Substantively, this mitigation effect is in the order of 0.14 metric tons of CO2 per capita and, thus, quite substantial. We also observe similar effects for more broadly defined environmental footprint measures. Overall, the evidence we present is consistent with the expectation that democracy helps in protecting lower-income countries against disproportionately accumulating polluting economic activity in an open global economy.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_pollution havens2.jpeg',
    tags: ['Publication'],
    link: '/research/pollution-havens',
    journal: "The Journal of Environment & Development",
    authors: 'Thomas Bernauer, Tobias Böhmelt, Ella Henninger',
    date: '2025-06-01',
  },
  {
    id: '10',
    title: 'Persistent inequalities in global air quality monitoring should not delay pollution mitigation',
    description: 'Publication on inequalities in global air quality monitoring and implications for pollution mitigation.',
    abstract: 'Air pollution is a global health crisis that disproportionately affects lower- and middle-income countries. We examine global air quality monitoring data, highlighting persistent inequalities in high-exposure regions, and assess the potential of emerging technologies to improve data utility for mitigation. Improving air quality, however, does not need to wait for more data, nor will monitoring alone drive action. Immediate mitigation measures with broad cobenefits are needed now to reduce pollution, even in data-scarce settings.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_persistent inequalities.jpeg',
    tags: ['Publication'],
    link: '/research/persistent-inequalities',
    journal: "Proceedings of the National Academy of Sciences",
    authors: 'E. Keith Smith, Camille Fournier de Laurière, Ella Henninger',
    date: '2025-04-28',
  },
  {
    id: '11',
    title: 'Contextual Factors Shape Stakeholder Dynamics in Air Pollution Control - Insights from Six Majority World Cities',
    description: 'Paper on how context shapes which stakeholders are most influential in shaping governments` mitigation agendas. Currently under review at Global Environmental Politics.',
    abstract: 'Air pollution is a major global health hazard, causing millions of premature deaths annually, with the worst impacts in Majority World cities (structurally disadvantaged locales comprising most of the world’s population). In these contexts, diverse local conditions shape stakeholders’ ability to influence government mitigation efforts. Drawing on 63 semi-structured interviews with 72 air pollution experts and stakeholders in six highly polluted cities (Accra, Kampala, Johannesburg, Jakarta, Dhaka, Delhi), we examine how economic development, democratic governance, and data availability structure the influence of key actors—citizens, local advocates, economic elites, and country-external agencies—on government mitigation efforts. We find that governments remain primarily responsive to economic elites across levels of economic development. In the lowest-income case (Dhaka), external actors play a more pronounced role. Democratic governance enables broader stakeholder engagement, especially among citizens and local advocates. Data availability expands opportunities for influence but also provokes governmental counter-strategies. These dynamics underscore opportunities and constraints for stakeholder engagement in pollution governance.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_qual paper.png',
    tags: ['Work in progress'],
    link: '/research/contextual-stakeholder-influence',
    journal: undefined,
    authors: 'Ella Henninger, E. Keith Smith, Thomas Bernauer',
    date: '2025-05-09',
  },
  {
    id: '12',
    title: 'Shifting environmental pollution abroad contributes to lower emissions in democracies',
    description: 'Publication on how pollution offshoring improves environmental records of democracies.',
    abstract: 'Many studies suggest that democracies have, on average, a better environmental protection record than authoritarian states. But this debate is far from resolved. Hence, we take a closer look at an overlooked factor that may shed new light on the ambiguous claims and findings of the democracy-environment nexus: pollution offshoring. We hypothesize that democracies can improve their record and become “greener” not only through genuinely domestic environmental protection, but also through outsourcing environmental impacts of their consumption to other countries. Analyzing data on greenhouse gas emissions, pollution offshoring, and democracy for more than 160 countries since the 1990s, we report evidence that the offshoring of environmental pollution contributes to the superior environmental record of democracies. The main policy implication is that democracies, per se, may not have a better environmental record than autocracies when considering global environmental impacts. This implies that democratic countries, in particular, should re-orient their environmental protection efforts from merely domestic to global environmental consequences of local economic activity.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_shifting pollution.jpeg',
    tags: ['Publication'],
    link: '/research/shifting-pollution',
    journal: 'PLOS Climate',
    authors: 'Thomas Bernauer, Tobias Böhmelt, Ella Henninger',
    date: '2025-05-14',
  },
  {
    id: '13',
    title: 'Strong demand for clean air policies in emerging markets and developing economies',
    description: 'Paper on perceptions of air pollution and support for mitigation policies in four Majority World cities.',
    abstract: 'Air pollution is a leading health risk, especially in emerging markets and developing economies. Yet, it remains unclear whether citizens will demand mitigation, perceive it as a threat, or view poor air quality as a necessary part of development. Competing theories predict either strong or weak support, and cross-national evidence is scarce, particularly for measures of policy support. We surveyed 11,562 adults in four severely polluted cities — Accra, Delhi, Jakarta, and Johannesburg. Air quality was a highly prioritised issue, and overall levels of concern are very high. Majorities support six mitigation proposals, including cost-salient measures such as stricter industrial limits, increasing household electrification, and expanding public transport. Concern, trust, and low perceived behavioural control were the strongest correlates of support. People see air pollution, feel its effects, and want governments to act, even when action entails economic costs, challenging views of limited environmental demand in highly exposed, economically developing settings.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_strong demand.png',
    tags: ['Work in progress'],
    link: '/research/strong-demand',
    journal: undefined,
    authors: 'E. Keith Smith, Ella Henninger, Camille Fournier de Laurière, Vally Koubi, Raeesa Moolla, Liam Beiser-McGrath, Thomas Bernauer',
    date: '2025-07-02',
  },
  {
    id: '14',
    title: '(Un)fair to Me - (Un)fair to You? Distributional Implications of Policies and Their Effect on Policy Support',
    description: 'Paper project on how different distributional policy designs shape fairness perceptions and support in Delhi and Jakarta.',
    abstract: '',
    thumbnail: 'src/assets/Thumbnails/thumbnail_fairness.png',
    tags: ['Work in progress'],
    link: '/research/fairness',
    journal: undefined,
    authors: 'Ella Henninger, Liam Beiser-McGrath, Vally Koubi',
    date: '2025-01-02',
  },
  {
    id: '15',
    title: 'Building Bridges: Actor Involvement as a Remedy for Trust Deficits in Environmental Policy Support',
    description: 'Paper project on the role of actor involvement in increasing policy support among low-trusting individuals in Accra, Johannesburg, Jakarta, and Delhi.',
    abstract: 'Trust in government is a key determinant of public policy support but is difficult to build. This paper tests whether inclusive policy design—through the involvement of local experts, citizens, international organisations, or business actors—can increase support even among low-trusting individuals. A pre-registered survey experiment in four polluted cities (Accra, Johannesburg, Jakarta, Delhi) varied who designed air pollution policy: government alone, a small coalition (government plus trusted actor), or a big coalition. Inclusive design significantly increased support, especially among those with low trust. Involving even a single trusted non-governmental actor raised support to levels comparable with broader coalitions. Mediation analysis shows that perceived policy effectiveness, not procedural fairness, drives this effect. The findings highlight actor involvement as a practical strategy for building support when political trust is low.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_trust.png',
    tags: ['Work in progress'],
    link: '/research/trust',
    journal: undefined,
    authors: 'Ella Henninger',
    date: '2025-01-01',
  },
  {
    id: '16',
    title: 'Pollution, Government (Dis)satisfaction, and Demand for Abatement Policies',
    description: 'Paper project on the effect of pollution on political attitudes in Accra, using daily variation in pollution levels as plausibly exogeneous treatment.',
    abstract: '',
    thumbnail: 'src/assets/Thumbnails/thumbnail_jop_accra.jpeg',
    tags: ['Work in progress'],
    link: '/research/jop',
    journal: undefined,
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2025-01-03',
  },
  {
    id: '17',
    title: 'When trust falters, are citizens expected to carry the load? Political trust and pollution responsibility attribution across African contexts',
    description: 'Work in progress. We intend to study how trust shapes who citizens believe to be responsible for pollution mitigation.',
    abstract: 'This paper investigates how political trust shapes citizens’ perceptions of who is responsible for mitigating environmental pollution across African contexts. Despite strong public demand for further government abatement efforts (64% of Afrobarometer respondents say governments should do much more to reduce pollution), 47% nonetheless believe that reducing pollution is primarily the responsibility of ordinary citizens. We argue that this disconnect between what people want governments to do and who they believe is responsible reflects varying levels of trust in government. People with low political trust have fewer expectations of state action, undermining demand for government-led mitigation and shifting perceived responsibility toward private behaviour. The analysis combines data from Afrobarometer Wave 9 (2021–23), covering 39 African countries, with two original urban surveys conducted in Accra and Johannesburg (2025). Using multi-level regression models, we assess how individual and contextual political trust shape responsibility attributions while accounting for demographic, political, economic, and environmental factors. The findings add to research on the consequences of political trust by showing how eroding trust privatises collective problems and weakens demand for state-led environmental action.',
    thumbnail: 'src/assets/Thumbnails/thumbnail_afrobarometer.jpeg',
    tags: ['Work in progress'],
    link: '/research/afrobarometer',
    journal: undefined,
    authors: 'Ella Henninger, E. Keith Smith',
    date: '2025-01-04',
  }
];
